
[font]
size=12

[font.normal]
family="JetBrainsMono"
style="Regular"

[font.bold]
family="JetBrainsMono"
style="Bold"

[font.italic]
family="JetBrainsMono"
style="Italic"

[font.bold_italic]
family="JetBrainsMono"
style="Bold Italic"


[scrolling]
history=100000
multiplier=3

[window]
option_as_alt="Both"

[window.padding]
x=3
y=3
